"""Structural merge operation for disjoint TeAL table artifacts.

``merge`` is deliberately not a Translator. It creates a new keys-only artifact
whose primary-key universe is the ordered concatenation of compatible, disjoint
basis artifacts. Structural key fields (``_position``, ``_batch``, and
``_row_offset``) are regenerated by ``ArtifactWriter``; representation data and
inherited metadata remain on the basis branches and are resolved lazily by the
query engine through ``merged_key`` lineage.

Incremental workflow extension / appending genuinely new observations is a
future use case and is intentionally not implemented here.
"""

from __future__ import annotations

import json
import os
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any

from text_analysis_lab.core.errors import ArtifactError
from text_analysis_lab.core.ids import next_id
from text_analysis_lab.core.lineage import validate_primary_key_relationship
from text_analysis_lab.core.operator import (
    BaseOperator,
    OutputSpec,
    TranslationRequest,
    validate_output_label,
)
from text_analysis_lab.core.types import ArtifactType, DEFAULT_OUTPUT_LABEL
from text_analysis_lab.core.writer import create_artifact_writer

if TYPE_CHECKING:
    from text_analysis_lab.core.artifact_base import BaseArtifact
    from text_analysis_lab.core.project import Project


class MergeOperator(BaseOperator):
    """Durable operator snapshot identifying TeAL's native structural merge."""

    operation_type = "merge"

    def output_specs(
        self,
        *,
        sources: Mapping[str, "BaseArtifact"],
        request: TranslationRequest,
    ) -> Mapping[str, OutputSpec]:
        _ = request
        if len(sources) < 2:
            raise ArtifactError("Merge requires at least two source artifacts.")
        first = next(iter(sources.values()))
        return {
            DEFAULT_OUTPUT_LABEL: OutputSpec(
                artifact_type=first.artifact_type,
                lineage_mode="merged_key",
                basis_labels=tuple(sources),
            )
        }


def merge(
    project: "Project",
    sources: Sequence["BaseArtifact | str"],
    *,
    output_label: str = DEFAULT_OUTPUT_LABEL,
    batch_size: int = 10_000,
    memo: str | None = None,
) -> "BaseArtifact":
    """Merge compatible, disjoint table artifacts into a keys-only artifact.

    Source order is durable and defines merged row order. Within each source,
    existing artifact order is preserved. The operation writes only the merged
    key component; representation data and metadata are never copied.

    Version-one scope is intentionally limited to ``TableArtifact`` sources.
    This covers split/process/recombine corpus workflows without prematurely
    defining lazy merge semantics for matrix/OTHER representations.
    """
    resolved = _resolve_sources(project, sources)
    output_label = validate_output_label(output_label)
    batch_size = _validate_batch_size(batch_size)
    _validate_sources(project, resolved)

    operator = MergeOperator()
    operator_id = next_id(project.storage.manifest_path, "operator")
    operator.assign_operator_id(operator_id)
    project.catalog.register_operator(
        operator_id=operator_id,
        operation_type="merge",
        snapshot_status="pending",
    )
    try:
        operator.save_to_dir(
            project.storage.operator_dir(operator_id),
            operator_id=operator_id,
        )
        project.catalog.mark_operator_serialized(operator_id)
    except Exception:
        project.catalog.mark_operator_snapshot_failed(operator_id)
        raise

    operation_id = next_id(project.storage.manifest_path, "operation")
    operation_dir = project.storage.operation_dir(operation_id)
    operation_dir.mkdir(parents=True, exist_ok=True)
    project.catalog.register_operation(
        operation_id=operation_id,
        operation_type="merge",
        operator_id=operator_id,
        status="incomplete",
    )
    for index, source in enumerate(resolved):
        project.catalog.add_operation_source(
            operation_id,
            f"source_{index:04d}",
            source.artifact_id,
        )

    artifact_id = next_id(project.storage.manifest_path, "artifact")
    basis_ids = [source.artifact_id for source in resolved]
    artifact_type = resolved[0].artifact_type
    project.catalog.register_artifact(
        artifact_id=artifact_id,
        artifact_type=artifact_type,
        label=output_label,
        lineage_mode="merged_key",
        status="incomplete",
        basis_artifact_ids=basis_ids,
    )
    project.catalog.add_operation_output(
        operation_id,
        output_label,
        artifact_id,
        ordinal=0,
    )

    writer = create_artifact_writer(
        artifact_type=artifact_type,
        artifact_dir=project.storage.artifact_dir(artifact_id),
        artifact_id=artifact_id,
        label=output_label,
        operation_id=operation_id,
        lineage_mode="merged_key",
        basis_artifact_ids=basis_ids,
    )

    descriptor = {
        "schema_version": 1,
        "operation_id": operation_id,
        "operation_type": "merge",
        "operator_id": operator_id,
        "status": "incomplete",
        "resumable": False,
        "source_order": basis_ids,
        "sources": {
            f"source_{index:04d}": source.artifact_id
            for index, source in enumerate(resolved)
        },
        "output_artifact_ids": {output_label: artifact_id},
        "request": {
            "output_label": output_label,
            "batch_size": batch_size,
        },
        "scope": "local_structural_merge",
        "incremental_append_supported": False,
    }
    _write_json(operation_dir / "operation.json", descriptor)

    try:
        if memo is not None:
            project.catalog.add_memo(
                target_type="operation",
                target_id=operation_id,
                body=memo,
            )

        for source in resolved:
            batches = source.query(
                key_columns=True,
                data_columns=False,
                metadata_columns=False,
                metadata_mode="none",
                order_by="_position",
                form="table",
                iter_batches=True,
                batch_size=batch_size,
                include_position=False,
            )
            for frame in batches:
                if frame.empty:
                    continue
                writer.write({"keys": frame.loc[:, list(source.primary_key)]})

        writer.finalize()
        validate_primary_key_relationship(
            basis_keys=[source.primary_key for source in resolved],
            output_key=resolved[0].primary_key,
            lineage_mode="merged_key",
        )
        project.catalog.mark_artifact_complete(artifact_id)
        project.catalog.mark_operation_complete(operation_id)
        descriptor["status"] = "complete"
        _write_json(operation_dir / "operation.json", descriptor)
        project.storage.touch_manifest()
        return project.get_artifact(artifact_id)
    except Exception as exc:
        try:
            writer.mark_failed(exc)
        except Exception:
            pass
        try:
            project.catalog.mark_artifact_failed(artifact_id)
        except Exception:
            pass
        try:
            project.catalog.mark_operation_failed(operation_id, exc)
        except Exception:
            pass
        descriptor["status"] = "failed"
        descriptor["error"] = f"{exc.__class__.__name__}: {exc}"
        _write_json(operation_dir / "operation.json", descriptor)
        raise


def _resolve_sources(
    project: "Project",
    sources: Sequence["BaseArtifact | str"],
) -> list["BaseArtifact"]:
    if isinstance(sources, (str, bytes)):
        raise ArtifactError("merge sources must be a sequence of artifact refs.")
    resolved = [project.get_artifact(source) for source in sources]
    if len(resolved) < 2:
        raise ArtifactError("merge requires at least two source artifacts.")
    return resolved


def _validate_sources(project: "Project", sources: Sequence["BaseArtifact"]) -> None:
    first = sources[0]
    first.require_complete()

    if first.artifact_type != ArtifactType.TABLE:
        raise ArtifactError(
            "The initial structural merge implementation supports table artifacts only; "
            f"got {first.artifact_type.value!r}."
        )

    expected_type = first.artifact_type
    expected_pk = tuple(first.primary_key)
    if not expected_pk:
        raise ArtifactError("merge source artifacts must have a primary key.")

    for source in sources[1:]:
        source.require_complete()
        if source.artifact_type != expected_type:
            raise ArtifactError(
                "merge sources must have the same artifact type: "
                f"expected {expected_type.value!r}, got {source.artifact_type.value!r} "
                f"for {source.artifact_id}."
            )
        if tuple(source.primary_key) != expected_pk:
            raise ArtifactError(
                "merge sources must use exactly the same primary-key fields in the "
                f"same order: expected {list(expected_pk)}, got "
                f"{list(source.primary_key)} for {source.artifact_id}."
            )

    # Validate the effective relational schema before any output IDs are created.
    # This is intentionally strict for v1. In particular, full metadata must
    # resolve to the same logical columns on every branch.
    expected = _effective_schema(project, first)
    for source in sources[1:]:
        actual = _effective_schema(project, source)
        if actual != expected:
            raise ArtifactError(
                "merge sources must have compatible effective data/full-metadata "
                f"schemas. {first.artifact_id} resolves {expected}, while "
                f"{source.artifact_id} resolves {actual}."
            )


def _effective_schema(
    project: "Project", artifact: "BaseArtifact"
) -> tuple[tuple[str, str, str], ...]:
    columns = project.query.query_columns(artifact, metadata_mode="full")["columns"]
    return tuple(
        (
            str(column["namespace"]),
            str(column["base_name"]),
            str(column["qualified_name"]),
        )
        for column in columns
        if str(column["namespace"]) != "key"
    )


def _validate_batch_size(value: int) -> int:
    try:
        resolved = int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError("batch_size must be a positive integer.") from exc
    if resolved <= 0:
        raise ValueError("batch_size must be a positive integer.")
    return resolved


def _write_json(path: Path, data: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(dict(data), indent=2, sort_keys=True)
    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
            temp_path = Path(handle.name)
        os.replace(temp_path, path)
    finally:
        if temp_path is not None and temp_path.exists():
            temp_path.unlink()
